// Copyright (C) 2026 Rob Caelers <robc@krandor.nl>
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef WORKRAVE_CORENEXT_RPC_DBUS_SERVER_HH
#define WORKRAVE_CORENEXT_RPC_DBUS_SERVER_HH

#include <memory>

#include "config/IConfigurator.hh"
#include "dbus/IDBus.hh"
#include "RpcDBusNames.hh"

class Core;

// Owns the DBus bindings generated by libs/rpc and their exact legacy-wire
// compatibility facades. When the legacy implementation is enabled this
// server uses an independent IDBus routing table and collision-free service
// and object names; otherwise it reuses the primary bus and legacy names.
class RpcDBusServer
{
public:
  RpcDBusServer(Core &core,
                workrave::config::IConfigurator &configurator,
                std::shared_ptr<workrave::dbus::IDBus> primary_bus,
                bool legacy_dbus_enabled);
  ~RpcDBusServer();

  RpcDBusServer(const RpcDBusServer &) = delete;
  RpcDBusServer &operator=(const RpcDBusServer &) = delete;

  [[nodiscard]] const RpcDBusNames &names() const;

private:
  struct Impl;
  std::unique_ptr<Impl> impl_;
};

#endif // WORKRAVE_CORENEXT_RPC_DBUS_SERVER_HH
