// Copyright (C) 2026 Rob Caelers <robc@krandor.nl>
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef WORKRAVE_CORENEXT_RPC_DBUS_SERVER_HH
#define WORKRAVE_CORENEXT_RPC_DBUS_SERVER_HH

#include <memory>

#include "config/IConfigurator.hh"
#include "dbus/IDBus.hh"

class Core;

// Owns the DBus bindings generated by libs/rpc and their compatibility
// facades. This is the sole Core/Break/Config implementation whenever RPC and
// DBus are enabled, so it uses the primary bus and established object paths.
class RpcDBusServer
{
public:
  RpcDBusServer(Core &core, workrave::config::IConfigurator &configurator, std::shared_ptr<workrave::dbus::IDBus> bus);
  ~RpcDBusServer();

  RpcDBusServer(const RpcDBusServer &) = delete;
  RpcDBusServer &operator=(const RpcDBusServer &) = delete;

private:
  struct Impl;
  std::unique_ptr<Impl> impl_;
};

#endif // WORKRAVE_CORENEXT_RPC_DBUS_SERVER_HH
