Import('env')
env = env.Copy()
env.Append(CPPPATH=['#backend/include', 'win32',
                    '#frontend/common/include',
                    '#common/win32/harpoon/include'])

src = ['SoundPlayer.cc',
       'System.cc',
       'Text.cc',
       'TimerBoxControl.cc',
       'win32/W32SoundPlayer.cc']
env.Library('workrave-frontend-common', src)