Import('env')
env = env.Copy()

src = ['GUI.cc', 'main.cc']
env.Append(CPPPATH=['#backend/include',
                    '#common/include'])
env.Append(LIBPATH=['#backend/src',
                    '#common/src',
                    '$QTDIR/lib',
                    '#common/win32/harpoon/src'])
env.Append(LIBS=['backend', 'common',
                 'QtGui4','QtCore4',
                 'harpoon',
                 'ole32',
                 'shlwapi'])

#env.Append(LINKFLAGS = '-mwindows')
env.Program('workrave', src)