Import('env')

env = env.Copy()
env.Append(CPPPATH=['../include'])

src = ['ActivityMonitor.cc',
       'Break.cc',
       'BreakControl.cc',
       'Configurator.cc',
       'Core.cc',
       'CoreFactory.cc',
       'QtIniConfigurator.cc',
       'QtNativeConfigurator.cc',
       'QtSettingsConfigurator.cc',
       'Statistics.cc',
       'Timer.cc']
env.Append(CPPPATH=['$WR_ARCH'])
env.Library('backend', src)