Import('env')

env = env.Copy()
env.Append(CPPPATH=['../include',
                    '#common/win32/harpoon/include/'])

src = ['ActivityMonitor.cc',
       'Break.cc',
       'BreakControl.cc',
       'Configurator.cc',
       'Core.cc',
       'CoreFactory.cc',
       'QtIniConfigurator.cc',
       'QtNativeConfigurator.cc',
       'QtSettingsConfigurator.cc',
       'Statistics.cc',
       'Timer.cc',
       'win32/Win32InputMonitor.cc']
env.Append(CPPPATH=['$WR_ARCH'])
env.Library('backend', src)