#include <Bonobo.idl>

module GNOME
{
  module Workrave
  {
    interface AppletControl : Bonobo::Unknown
    {
      long get_socket_id();
      long get_size();
      long get_orientation();

      void set_menu_status(in string menu, in boolean status);
      boolean get_menu_status(in string menu);

      void set_menu_active(in string menu, in boolean status);
      boolean get_menu_active(in string menu);
    };
  };
};
