.TH "WORKRAVE" "1" "26 February 2003" "" ""

.SH NAME
workrave \- RSI prevention tool
.SH SYNOPSIS

\fBworkrave\fR

.SH "DESCRIPTION"
.PP
Workrave is a tool that reminds you to take regular breaks,
thus preventing RSI or helping you to recover from it.
.SH "OPTIONS"
.PP
Workrave does not take any options besides the standard GNOME options.
.SH "AUTHOR"
.PP
This manual page was written by Michael Piefel <piefel@debian.org> for
the Debian GNU/Linux system (but may be used by others).
