function(workrave_collect_targets directory output)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    workrave_collect_targets("${child}" child_targets)
    list(APPEND targets ${child_targets})
  endforeach()
  set(${output} ${targets} PARENT_SCOPE)
endfunction()

function(workrave_std_pch)
  workrave_collect_targets("${CMAKE_SOURCE_DIR}" targets)
  foreach(target IN LISTS targets)
    get_target_property(type ${target} TYPE)
    if(type STREQUAL "INTERFACE_LIBRARY" OR type STREQUAL "UTILITY")
      continue()
    endif()
    get_target_property(sources ${target} SOURCES)
    set(count 0)
    foreach(source IN LISTS sources)
      if(source MATCHES "\\.(cc|cpp|cxx)$")
        math(EXPR count "${count}+1")
      endif()
    endforeach()
    if(count GREATER_EQUAL 12 OR target STREQUAL "unfold-http")
      target_precompile_headers(${target} PRIVATE
        "$<$<COMPILE_LANGUAGE:CXX>:${CMAKE_CURRENT_FUNCTION_LIST_DIR}/std-pch.hh>")
      if(target STREQUAL "libprotobuf")
        target_precompile_headers(${target} PRIVATE <google/protobuf/message.h>)
      elseif(target STREQUAL "unfold-http")
        target_precompile_headers(${target} PRIVATE <boost/asio.hpp> <boost/beast.hpp>)
      elseif(target STREQUAL "workrave-toolkit-qt")
        target_precompile_headers(${target} PRIVATE <QtWidgets> <QtQuick> <boost/asio.hpp>)
      elseif(target STREQUAL "sigstore")
        target_precompile_headers(${target} PRIVATE <boost/json.hpp>)
      endif()
      message(STATUS "Precompiled headers: ${target} (${count} C++ sources)")
    endif()
  endforeach()
endfunction()
cmake_language(DEFER CALL workrave_std_pch)
