Import('env')
env = env.Copy()
src = ['DayTimePred.cc',
       'TimePredFactory.cc',
       'WeekTimePred.cc',
       'debug.cc',
       'Util.cc',
       'win32/gettimeofday.c']
env.Library('common', src)