#include <Bonobo.idl>

module GNOME
{
  module Workrave
  {
    interface WorkraveControl : Bonobo::Unknown
    {
      enum Mode { MODE_INVALID, MODE_NORMAL, MODE_SUSPENDED, MODE_QUIET };

      oneway void fire();
      
      oneway void open_main();
      oneway void open_preferences();
      oneway void open_network_connect();
      oneway void open_statistics();
      oneway void open_network_log(in boolean state);
      
      oneway void restbreak();
      oneway void set_mode(in Mode mode);
      oneway void disconnect_all();
      oneway void reconnect_all();
      oneway void quit();

      oneway void set_applet_vertical(in boolean vertical);
      oneway void set_applet_size(in long size);
      oneway void set_applet(in Bonobo::Unknown applet);
      oneway void button_clicked(in long button);
    };
  };
};
