#include <Bonobo.idl>

module GNOME
{
  module Workrave
  {
    interface AppletControl : Bonobo::Unknown
    {
      long get_socket_id();
      long get_size();
      boolean get_vertical();
      void set_menu_status(in string menu, in boolean status);
      boolean get_menu_status(in string menu);
      boolean register_control(in Bonobo::Unknown control);
      boolean unregister_control(in Bonobo::Unknown control);
    };
  };
};
